# Google Cloud Build configuration
# Builds and deploys the Hotel Operator Agent to Cloud Run

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hotel-operator-agent:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hotel-operator-agent:latest'
      - '-f'
      - 'Dockerfile.production'
      - '.'
    id: 'build-image'

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/hotel-operator-agent:$SHORT_SHA'
    id: 'push-image-sha'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/hotel-operator-agent:latest'
    id: 'push-image-latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'westbethel-operator'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hotel-operator-agent:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ENV=production,PROJECT_ID=$PROJECT_ID,REGION=us-central1'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest,TWILIO_ACCOUNT_SID=twilio-account-sid:latest,TWILIO_AUTH_TOKEN=twilio-auth-token:latest,DATABASE_URL=database-url:latest,REDIS_URL=redis-url:latest'
    id: 'deploy-cloud-run'

# Images to be stored in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/hotel-operator-agent:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/hotel-operator-agent:latest'

# Build configuration
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build
timeout: '1200s'

# Substitutions
substitutions:
  _SERVICE_NAME: 'westbethel-operator'
  _REGION: 'us-central1'
