"""Initial migration

Revision ID: e5a98a45ec5d
Revises: 
Create Date: 2025-10-24 09:01:28.346310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a98a45ec5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('loyalty_tier', sa.String(length=50), nullable=True),
    sa.Column('loyalty_points', sa.Integer(), nullable=True),
    sa.Column('vip_status', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('hotel_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=False),
    sa.Column('setting_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_key')
    )
    op.create_table('inventory_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.Enum('STANDARD_QUEEN', 'KING_SUITE', 'PET_FRIENDLY', 'DELUXE_SUITE', name='roomtype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('rooms_blocked', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory_block_dates', 'inventory_blocks', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_inventory_block_room_type', 'inventory_blocks', ['room_type', 'start_date'], unique=False)
    op.create_table('rate_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('room_type', sa.Enum('STANDARD_QUEEN', 'KING_SUITE', 'PET_FRIENDLY', 'DELUXE_SUITE', name='roomtype'), nullable=False),
    sa.Column('rate_type', sa.Enum('STANDARD', 'WEEKEND', 'HOLIDAY', 'PEAK', 'OFF_PEAK', 'GROUP', 'CORPORATE', 'LAST_MINUTE', name='ratetype'), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('fixed_adjustment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rate_rule_dates', 'rate_rules', ['effective_date', 'end_date'], unique=False)
    op.create_index('idx_rate_rule_priority', 'rate_rules', ['priority', 'active'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=10), nullable=False),
    sa.Column('room_type', sa.Enum('STANDARD_QUEEN', 'KING_SUITE', 'PET_FRIENDLY', 'DELUXE_SUITE', name='roomtype'), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('max_adults', sa.Integer(), nullable=False),
    sa.Column('max_children', sa.Integer(), nullable=False),
    sa.Column('pet_friendly', sa.Boolean(), nullable=True),
    sa.Column('smoking_allowed', sa.Boolean(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('square_footage', sa.Integer(), nullable=True),
    sa.Column('bed_configuration', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_number')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmation_number', sa.String(length=20), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.Time(), nullable=True),
    sa.Column('check_out_time', sa.Time(), nullable=True),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=True),
    sa.Column('infants', sa.Integer(), nullable=True),
    sa.Column('pets', sa.Boolean(), nullable=True),
    sa.Column('pet_count', sa.Integer(), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', 'NO_SHOW', name='bookingstatus'), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PARTIAL', 'PAID', 'REFUNDED', 'FAILED', name='paymentstatus'), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fees_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('balance_due', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rate_type', sa.Enum('STANDARD', 'WEEKEND', 'HOLIDAY', 'PEAK', 'OFF_PEAK', 'GROUP', 'CORPORATE', 'LAST_MINUTE', name='ratetype'), nullable=False),
    sa.Column('rate_per_night', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_reference', sa.String(length=100), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancellation_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmation_number')
    )
    op.create_index('idx_booking_dates', 'bookings', ['check_in_date', 'check_out_date'], unique=False)
    op.create_index('idx_booking_guest', 'bookings', ['guest_id', 'created_at'], unique=False)
    op.create_index('idx_booking_status', 'bookings', ['status', 'payment_status'], unique=False)
    op.create_table('room_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('total_inventory', sa.Integer(), nullable=True),
    sa.Column('booked_count', sa.Integer(), nullable=True),
    sa.Column('available_count', sa.Integer(), nullable=True),
    sa.Column('maintenance', sa.Boolean(), nullable=True),
    sa.Column('overbooked', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_availability_date', 'room_availability', ['date', 'available'], unique=False)
    op.create_index('idx_availability_room_date', 'room_availability', ['room_id', 'date'], unique=False)
    op.create_table('room_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('rate_type', sa.Enum('STANDARD', 'WEEKEND', 'HOLIDAY', 'PEAK', 'OFF_PEAK', 'GROUP', 'CORPORATE', 'LAST_MINUTE', name='ratetype'), nullable=False),
    sa.Column('base_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('min_nights', sa.Integer(), nullable=True),
    sa.Column('max_nights', sa.Integer(), nullable=True),
    sa.Column('advance_booking_days', sa.Integer(), nullable=True),
    sa.Column('cancellation_hours', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_room_rate_dates', 'room_rates', ['room_id', 'effective_date', 'end_date'], unique=False)
    op.create_index('idx_room_rate_type', 'room_rates', ['rate_type', 'effective_date'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'PAID', 'REFUNDED', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_index('idx_room_rate_type', table_name='room_rates')
    op.drop_index('idx_room_rate_dates', table_name='room_rates')
    op.drop_table('room_rates')
    op.drop_index('idx_availability_room_date', table_name='room_availability')
    op.drop_index('idx_availability_date', table_name='room_availability')
    op.drop_table('room_availability')
    op.drop_index('idx_booking_status', table_name='bookings')
    op.drop_index('idx_booking_guest', table_name='bookings')
    op.drop_index('idx_booking_dates', table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('rooms')
    op.drop_index('idx_rate_rule_priority', table_name='rate_rules')
    op.drop_index('idx_rate_rule_dates', table_name='rate_rules')
    op.drop_table('rate_rules')
    op.drop_index('idx_inventory_block_room_type', table_name='inventory_blocks')
    op.drop_index('idx_inventory_block_dates', table_name='inventory_blocks')
    op.drop_table('inventory_blocks')
    op.drop_table('hotel_settings')
    op.drop_table('guests')
    # ### end Alembic commands ###
